### PR TITLE
New Hunger Games lobby system

### PR DESCRIPTION
**Pull request by RubenJ01**
I have fixed some minor bugs and moved around some files but most importantly replaced the old hunger games lobby with the new lobby system we are using, Would like for you to take a look and see if I missed some things or if I need to change some things.

### CODE REVIEW

**Review by gaborszita — CHANGES_REQUESTED** [review]
- You should do a check at fill lobby and check if the AbstractLobby instance is instance of BotLobby. I know it _should_ be an instance of it, but based on how complicated this lobby handling is and can get in the future, we should better be safe than sorry and throw a ClassCastException with a nice message, so debugging can be easier in the future.
- In LobbyEntry, you should move from string ids to long ids, if possible. This is completely up to you, though, if it would be a huge refactor then you don't have to do it. I am just saying if it isn't much work, you should do it, but it is completely fine if you leave it like that (for now).
- Consider moving NonPlayerCharacter from the models package as a static inner class of BotLobby. It's a relatively small file, so I don't see why we should clutter the already complicated and a bit messy file structure with one more class, in the models package, in which we are basically putting now every class that is simply helper class.

EDIT: Removed first bullet point, just noticed you already fixed it, I just didn't see it as I skimmed through the files. Added one more consideration. Also fixed some typos.

**Comment by RubenJ01** [comment]
> * You should do a check at fill lobby and check if the AbstractLobby instance is instance of BotLobby. I know it _should_ be an instance of it, but based on how complicated this lobby handling is and can get in the future, we should better be safe than sorry and throw a ClassCastException with a nice message, so debugging can be easier in the future.

You're right, initially I thought that this button would only be added on BotLobby embeds but in the small chance that something goes wrong its still worth checking.

> * In LobbyEntry, you should move from string ids to long ids, if possible. This is completely up to you, though, if it would be a huge refactor then you don't have to do it. I am just saying if it isn't much work, you should do it, but it is completely fine if you leave it like that (for now).

Yeah this is something I just forgot. Those user id's arent even changed at the moment but later they will be used when I implement some detailed stat tracking. So I went ahead and changed it.

> * Consider moving NonPlayerCharacter from the models package as a static inner class of BotLobby. It's a relatively small file, so I don't see why we should clutter the already complicated and a bit messy file structure with one more class, in the models package, in which we are basically putting now every class that is simply helper class.

Agreed, NonPlayerCharacter also wont be used anywhere else so it makes sense to have it there.

> * In BotLobby, don't you want to reset the idle instance cleanup of the lobby at fill? I don't know how the logic works, I'm just asking in case you just forgot to add it.

Did not think about this so thanks. Ive changed this as well.

**Comment by gaborszita** [comment]
I'll make a few minor fixed and then merge it. Should get them in by 10 PM-UTC 9/7/22 today.

**Comment by RubenJ01** [comment]
> I'll make a few minor fixes and then merge it. Should get them in by 10 PM-UTC 9/7/22 today.

Perfect. Il get working on completely getting rid of the old database.

**Review by gaborszita — APPROVED** [review]

**Pull request merged**
